name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'samples/**'
      - '.gitattributes'
      - '.gitignore'
      - '.clang-format'
      - '.clang-tidy'
      - '.cmake-format.yaml'
      - 'LICENCE'
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'samples/**'
      - '.gitattributes'
      - '.gitignore'
      - '.clang-format'
      - '.clang-tidy'
      - '.cmake-format.yaml'
      - 'LICENCE'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Ninja
      uses: turtlesec-no/get-ninja@main

    - name: Install GCC 12
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 12

    - name: Configure CMake
      run: cmake -S . -G "Ninja" --preset="unixlike-gcc-debug" -D ENABLE_CPPCHECK=OFF
      env:
        CC:   gcc-12
        CXX:  g++-12

    - name: Build
      run: cmake --build ./build/unixlike-gcc-debug

    - name: Test
      working-directory: ./build/unixlike-gcc-debug
      run: ctest
